/** Bilingual copy for organizer / supplier portal (trip flows, buttons, errors). */

export const PORTAL_COPY = {
  en: {
    shared: {
      favorite: 'Favorite',
      favorited: 'Favorited',
      select: 'Select',
      continue: 'Continue',
      cancel: 'Cancel',
      messageOptional: 'Message (optional)',
      addContextSuppliers: 'Add context for suppliers…',
      addContextProvider: 'Add context for the provider…',
      needTypes: 'Need types',
      selectOneNeedType: 'Select at least one need type.',
      chooseOptions: 'Choose options',
      selectOneOption: 'Select at least one option.',
      pending: 'Pending',
      confirmed: 'Confirmed',
      provider: 'Provider',
      recommended: 'Recommended',
      accept: 'Accept',
      reject: 'Reject',
      withdraw: 'Withdraw',
      interfaceLanguage: 'Interface language',
      interfaceLanguageHint: 'Controls the app language and email notifications.',
    },
    tripDetail: {
      backAdmin: 'Back to All Trips',
      backProvider: 'Back to Available Trips',
      backOrganizer: 'Back to My Trips',
      tripNotFound: 'Trip not found.',
      fullPackage: 'Full package',
      platformAdminView: 'Platform admin view',
      itinerary: 'Itinerary',
      aboutTrip: 'About this trip',
      recommendedProviders: 'Recommended providers',
      recommendedSubtitle: 'Expert services tailored to your trip details',
      serviceRequests: 'Service requests',
      request: 'request',
      requests: 'requests',
      noServiceRequestsYet: 'No service requests yet for this trip.',
      openPackageRequest: 'Open package request',
      openPackageRequestTitle: 'Open package request',
      packageRequestBody:
        'This is a full-package group booking. One provider (typically the hotel) handles transport, stay, and transfers — you only need a single request.',
      servicesIncluded: (types) => ` Services included: ${types.join(', ')}.`,
      packageAlreadyOpen: 'A package request is already open for this trip.',
      packageAlreadyOpenError: 'The package request for this trip is already open.',
      confirmPackageRequest: 'Confirm package request',
      confirmRequest: 'Confirm request',
      openNewServiceRequest: 'Open a new service request',
      newRequestBody:
        'Notify suppliers that you need services for this trip. Select one or more need types — each opens a separate request so the right suppliers can respond.',
      tripTypesOnly: (types) => ` Only types defined for this trip are shown (${types.join(', ')}).`,
      allTypesHaveRequests: 'Every need type for this trip already has a service request.',
      allTypesHaveRequestsError: 'All need types for this trip already have an open request.',
      openRequest: 'Open request',
      openRequests: (count) => `Open ${count} requests`,
      confirmServiceRequests: 'Confirm service requests',
      confirmRequests: 'Confirm requests',
      selectOneNeedTypeError: 'Select at least one need type.',
      chooseTripTypes: (types) => `Choose need types listed on this trip: ${types.join(', ')}.`,
      createRequestFailed: 'Could not create the service request.',
      createPackageFailed: 'Could not create the package request.',
      partialRequestsFailed: (failed, total) =>
        `${failed} of ${total} requests could not be opened. The rest were created.`,
      changeCover: 'Change cover',
      deleteTrip: 'Delete trip',
      deleteTripTitle: 'Delete this trip?',
      deleteTripBody: (title) => `${title} will be permanently removed. This cannot be undone.`,
      deletePermanently: 'Delete permanently',
      activityWarning: (requests, offers) => {
        const reqPart = `${requests} service ${requests === 1 ? 'request' : 'requests'}`
        const offerPart =
          offers > 0 ? ` and ${offers} supplier ${offers === 1 ? 'offer' : 'offers'}` : ''
        return `This trip has ${reqPart}${offerPart}. Deleting will remove them as well.`
      },
    },
    createTrip: {
      continueWithoutImage: 'Continue without image',
      publishRequest: 'Publish Request',
      retryImageUpload: 'Retry image upload',
      selectOneServiceError: 'Select at least one service option in at least one step.',
      whatDoYouNeed: 'What do you need?',
      addStepsHint: 'Add as many steps as your route needs. Use “Add step” to continue.',
      step: (n) => `Step ${n}`,
      remove: 'Remove',
      serviceDate: 'Service date',
      from: 'From',
      to: 'To',
      addStep: 'Add step',
    },
    profile: {
      saveChanges: 'Save changes',
      changesSaved: 'Changes saved.',
    },
  },
  fr: {
    shared: {
      favorite: 'Favori',
      favorited: 'Favori',
      select: 'Sélectionner',
      continue: 'Continuer',
      cancel: 'Annuler',
      messageOptional: 'Message (facultatif)',
      addContextSuppliers: 'Ajouter du contexte pour les fournisseurs…',
      addContextProvider: 'Ajouter du contexte pour le fournisseur…',
      needTypes: 'Types de besoins',
      selectOneNeedType: 'Sélectionnez au moins un type de besoin.',
      chooseOptions: 'Choisir les options',
      selectOneOption: 'Sélectionnez au moins une option.',
      pending: 'En attente',
      confirmed: 'Confirmé',
      provider: 'Fournisseur',
      recommended: 'Recommandé',
      accept: 'Accepter',
      reject: 'Refuser',
      withdraw: 'Retirer',
      interfaceLanguage: "Langue de l'interface",
      interfaceLanguageHint: "Définit la langue de l'application et des e-mails.",
    },
    tripDetail: {
      backAdmin: 'Retour à tous les voyages',
      backProvider: 'Retour aux voyages disponibles',
      backOrganizer: 'Retour à mes voyages',
      tripNotFound: 'Voyage introuvable.',
      fullPackage: 'Forfait complet',
      platformAdminView: 'Vue administrateur plateforme',
      itinerary: 'Itinéraire',
      aboutTrip: 'À propos de ce voyage',
      recommendedProviders: 'Fournisseurs recommandés',
      recommendedSubtitle: 'Des services adaptés aux détails de votre voyage',
      serviceRequests: 'Demandes de service',
      request: 'demande',
      requests: 'demandes',
      noServiceRequestsYet: 'Aucune demande de service pour ce voyage.',
      openPackageRequest: 'Ouvrir une demande forfait',
      openPackageRequestTitle: 'Ouvrir une demande forfait',
      packageRequestBody:
        'Il s’agit d’une réservation de groupe en forfait. Un seul fournisseur (souvent l’hôtel) gère transport, hébergement et transferts — une seule demande suffit.',
      servicesIncluded: (types) => ` Services inclus : ${types.join(', ')}.`,
      packageAlreadyOpen: 'Une demande forfait est déjà ouverte pour ce voyage.',
      packageAlreadyOpenError: 'La demande forfait de ce voyage est déjà ouverte.',
      confirmPackageRequest: 'Confirmer la demande forfait',
      confirmRequest: 'Confirmer la demande',
      openNewServiceRequest: 'Ouvrir une nouvelle demande de service',
      newRequestBody:
        'Informez les fournisseurs des services dont vous avez besoin. Sélectionnez un ou plusieurs types de besoins — chaque type ouvre une demande distincte pour que les bons fournisseurs puissent répondre.',
      tripTypesOnly: (types) => ` Seuls les types définis pour ce voyage sont affichés (${types.join(', ')}).`,
      allTypesHaveRequests: 'Chaque type de besoin de ce voyage a déjà une demande de service.',
      allTypesHaveRequestsError: 'Tous les types de besoin de ce voyage ont déjà une demande ouverte.',
      openRequest: 'Ouvrir une demande',
      openRequests: (count) => `Ouvrir ${count} demandes`,
      confirmServiceRequests: 'Confirmer les demandes de service',
      confirmRequests: 'Confirmer les demandes',
      selectOneNeedTypeError: 'Sélectionnez au moins un type de besoin.',
      chooseTripTypes: (types) => `Choisissez les types listés pour ce voyage : ${types.join(', ')}.`,
      createRequestFailed: 'Impossible de créer la demande de service.',
      createPackageFailed: 'Impossible de créer la demande forfait.',
      partialRequestsFailed: (failed, total) =>
        `${failed} demande(s) sur ${total} n’ont pas pu être ouvertes. Les autres ont été créées.`,
      changeCover: 'Changer la couverture',
      deleteTrip: 'Supprimer le voyage',
      deleteTripTitle: 'Supprimer ce voyage ?',
      deleteTripBody: (title) => `${title} sera définitivement supprimé. Cette action est irréversible.`,
      deletePermanently: 'Supprimer définitivement',
      activityWarning: (requests, offers) => {
        const reqPart = `${requests} demande${requests === 1 ? '' : 's'} de service`
        const offerPart =
          offers > 0 ? ` et ${offers} offre${offers === 1 ? '' : 's'} fournisseur` : ''
        return `Ce voyage compte ${reqPart}${offerPart}. La suppression les effacera également.`
      },
    },
    createTrip: {
      continueWithoutImage: 'Continuer sans image',
      publishRequest: 'Publier la demande',
      retryImageUpload: 'Réessayer le téléversement',
      selectOneServiceError: 'Sélectionnez au moins une option de service dans au moins une étape.',
      whatDoYouNeed: 'De quoi avez-vous besoin ?',
      addStepsHint:
        'Ajoutez autant d’étapes que nécessaire. Utilisez « Ajouter une étape » pour continuer.',
      step: (n) => `Étape ${n}`,
      remove: 'Supprimer',
      serviceDate: 'Date du service',
      from: 'De',
      to: 'À',
      addStep: 'Ajouter une étape',
    },
    profile: {
      saveChanges: 'Enregistrer',
      changesSaved: 'Modifications enregistrées.',
    },
  },
}

export function getPortalCopy(locale) {
  return PORTAL_COPY[locale === 'fr' ? 'fr' : 'en']
}
